### ISSUE TITLE
push的ViewController会覆盖tabbar

### ISSUE THREAD

**Issue by siegrainwong** [shuoshi/HHNavigationController#5]
在`HHNavigationController.m`的`pushViewController`方法中。
有以下代码会导致这个问题

```
if (self.viewControllers.count > 0) {
    viewController.hidesBottomBarWhenPushed = YES;
}
```

而我注释这段代码后也没有出现什么其他Bug，不是很明白这段代码的意义。

**Comment by roodkcab** [comment]
这句代码的意思就是要让viewController在push进来的时候覆盖tabbar，这里没有预留配置做不覆盖的更改

**Comment by siegrainwong** [comment]
我当然知道这个代码的作用是什么，只是正常来说，这个设置应该让用户来决定比较好。
