### ISSUE TITLE
pods 使用出错

### ISSUE THREAD

**Issue by iostalks** [shuoshi/HHNavigationController#6]
在 Podfile 新的书写格式中，安装失败。

> Pre-downloading: `HHNavigationController` from `https://github.com/shuoshi/HHNavigationController`, commit `d8e5bcece933f59f3af29aa01e337e59d0a19922`
> [!] The `HHNavigationController` pod failed to validate due to 1 error:
>     - ERROR | description: The description is empty.

**Comment by roodkcab** [comment]
update podspec desc field
